---
application:
  name: "video-call-backend"
  project: "first-project"
  organization: "QoveryCommunity"
routers:
- name: "main-video-call-backend"
  routes:
  - application_name: "video-call-backend"
    paths:
    - "/*"
